version: '3'

services:

  java-quarkus-sample1-app1:
    container_name: java-quarkus-sample1-app1
    image: helpdev/java-quarkus-sample1-jvm
    environment:
      APPLICATION_NAME: java-quarkus-sample1-app1
      HTTP_PORT: 8080
      CALL_OTHER_SERVICE_ENABLED: 'true'
      CALL_OTHER_SERVICE_HOST: http://java-quarkus-sample1-app2:8081
      OT_TRACER_URL: http://collector-agent:4318
      OT_METRICS_EXPORTER_URL: http://collector-agent:4317/v1/metrics
      QUARKUS_LOG_LEVEL: INFO
      QUARKUS_OPENTELEMETRY_TRACER_RESOURCE_ATTRIBUTES: "service.name=java-quarkus-sample1-app1"
    ports: 
      - 8080:8080

  java-quarkus-sample1-app2:
    container_name: java-quarkus-sample1-app2
    image: helpdev/java-quarkus-sample1-jvm
    environment:
      APPLICATION_NAME: java-quarkus-sample1-app2
      HTTP_PORT: 8081
      CALL_OTHER_SERVICE_ENABLED: 'true'
      CALL_OTHER_SERVICE_HOST: http://java-quarkus-sample1-app3:8082
      OT_TRACER_URL: http://collector-agent:4318
      OT_METRICS_EXPORTER_URL: http://collector-agent:4317/v1/metrics
      QUARKUS_LOG_LEVEL: DEBUG
      QUARKUS_OPENTELEMETRY_TRACER_RESOURCE_ATTRIBUTES: "service.name=java-quarkus-sample1-app2"
    ports: 
      - 8081:8081

  java-quarkus-sample1-app3:
    container_name: java-quarkus-sample1-app3
    image: helpdev/java-quarkus-sample1-jvm
    environment:
      APPLICATION_NAME: java-quarkus-sample1-app3
      HTTP_PORT: 8082
      CALL_OTHER_SERVICE_ENABLED: 'false'
      OT_TRACER_URL: http://collector-agent:4318
      OT_METRICS_EXPORTER_URL: http://collector-agent:4317/v1/metrics
      QUARKUS_LOG_LEVEL: INFO
      QUARKUS_OPENTELEMETRY_TRACER_RESOURCE_ATTRIBUTES: "service.name=java-quarkus-sample1-app3"
    ports: 
      - 8082:8082

  jaeger:
    image: jaegertracing/all-in-one
    ports: 
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686 # UI
      - 14268:14268
      - 14250:14250
      - 9411:9411

  prometheus:
    image: prom/prometheus
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - 9090:9090

  collector-gateway:
    image: otel/opentelemetry-collector-contrib
    volumes: 
      - ./config/collector-gateway.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4320:4320"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension

  collector-agent:
    image: otel/opentelemetry-collector
    volumes: 
      - ./config/collector-agent.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"   # OTLP HTTP receiver
      - "4318:4318"   # OTLP gRPC receiver